# -*- coding: utf-8 -*-
"""face_detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ss4nuPEiLrukm-zt-5G8WHz8q5EvB_so

# Using Google Colab to run our machine learning projects.

### Change the directory to face_detection folder

First create a folder and name it as **face_detection**
"""

from google.colab import drive
drive.mount('/content/drive/')

"""use `os.chdir` to connect to the face_detection directory"""

from os import chdir
chdir('/content/drive/My Drive/face_detection')

!git clone https://github.com/ibm-cds-labs/pixiedust

"""### Clone your project in the google drive"""

!git clone https://github.com/masouduut94/Pytorch_Retinaface.git

"""Doing a little bit cleaning."""

!mv Pytorch_Retinaface/* ./
!rm -r Pytorch_Retinaface/

"""### Get the pretrained weight files
1 - We open the link to the pretrained models.

2 - We right click on the weight file and choose "Add Shortcut to Drive"

3 - Then we choose the `My drive/face_detection/weights` directory.

### Get a video for testing the code

1- Download the video from link

2- Extract the file into the upload folder
"""

!wget -O file.zip https://storage.coverr.co/videos/zip/Cinema_Paradiso?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBJZCI6IjExNDMyN0NEOTRCMUFCMTFERTE3IiwiaWF0IjoxNTg1MzE1MDMzfQ.Hafuhocv3bUpCKJ6l5MZlPfZO24fR9fwq_Yi0tr-vhQ
!mkdir temp 
!unzip file.zip -d temp

!mv temp/Cinema_Paradiso.mp4 upload/
!rm -r temp
!rm file.zip

"""### Run the `face_detection_server.py`

For your own projects install dependenscies
Google colab has installed the last version of tensorflow and pytorch for default
"""

!python face_detection_server.py --input=upload/Cinema_Paradiso.mp4

